---
  - name: Install spring boot application in docker environment
    hosts: azure-hosts

    tasks:

      - name: Ensure Docker Compose is available
        command: docker compose version
        register: compose_check
        failed_when: compose_check.rc != 0
        changed_when: false

      - name: Clone git repo
        git:
          repo: 'git@github.com:it2022057/devops-2025.git'
          dest: "{{ repo_dir }}"
          version: "{{ branch }}"
          force: yes
          accept_hostkey: yes
          recursive: yes
          update: yes
      
      - name: Remove file application.properties
        file:
          path: "{{ app_dir }}/src/main/resources/application.properties"
          state: absent
        tags:
          - edit

      - name: Copy application.yml instead of application.properties
        copy:
          src: ../files/application.yml
          dest: "{{ app_dir }}/src/main/resources/application.yml"
        tags:
          - edit
      # - name: "Populate application.properties"
      #   lineinfile:
      #     dest: "{{ app_dir }}/src/main/resources/application.properties"
      #     state: present
      #     regexp: "^{{item.key}}="
      #     line: "{{item.key}}={{item.value}}"
      #   with_items:
      #     - "{{app.env | dict2items}}"
      #   tags:
      #     - edit

      - name: Install pip3 
        apt:
          name: python3-pip
          state: latest
          update_cache: yes
        become: yes
        tags:
          - install

      - name: Install Docker SDK for Python
        command: pip3 install docker --break-system-packages
        become: yes
        tags:
          - install

      - name: Stop any existing containers
        community.docker.docker_compose_v2:
          project_src: "{{ repo_dir }}"
          state: absent
        tags:
          - stop
      
      - name: Start the containers written in the docker files
        community.docker.docker_compose_v2:
          project_src: "{{ repo_dir }}"
          build: always
          state: present
        register: output
        notify: Restart Docker Compose
        tags:
          - start
      
      - debug:
          var: output
    
    handlers:
    - name: Restart Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ repo_dir }}"
        state: restarted